### ISSUE TITLE
Feature Request: Allow the flashbar to show relative to other views such as Toolbar

### ISSUE THREAD

**Issue by aiavci** [aritraroy/Flashbar#10]
# Version
1.0.2

# Summary
Allow the flashbar to show relative to other views such as toolbar, navigation bar or footers.

# Description
Currently the flashbar only shows either at the top or bottom of the screen without leaving space for the other views.

**Comment by aritraroy** [comment]
This feature is actually on the roadmap where you can provide your custom parent layout to show the flashbar. Closing for now.

**Comment by ismdcf** [comment]
Is this feature implemented yet
