### ISSUE TITLE
Flutter version of Flashbar

### ISSUE THREAD

**Issue by AndreHaueisen** [aritraroy/Flashbar#14]
Hi @aritraroy. I passing by to let you know that I liked the idea so much that I'm developing a Flutter version of Flashbar: Flushbar.
It is still in early stages though. I hope I can make something as good as Flashbar. If you want to check it out, [Flushbar](https://pub.dartlang.org/packages/flushbar).

Cheers!

**Comment by aritraroy** [comment]
Sure. Will check it out.
