### ISSUE TITLE
Enhacement 

### ISSUE THREAD

**Issue by echopros** [aritraroy/Flashbar#16]
hi, how are you guys, thanks for this fantastic library. 

just want to know if there is a chance to add a feature so that the user will see the flashbar after some opportunities like after 3 launches of the app or 3 days, and once he clicked the positive button the FlashBar will never been shown again. 

otherwise. your app is greeeeeat

**Comment by aritraroy** [comment]
This is a very domain specific requirement and shouldn't be included as a general solution in this library IMO. You can easily achieve this behavior with the current implementation of the library.

**Comment by echopros** [comment]
Thank you 😁😁
