### ISSUE TITLE
Add buttons for samples in sample app

### ISSUE THREAD

**Issue by amitav13** [aritraroy/Flashbar#2]
It would be nice to have a list of all the various types of customisations available as a list of buttons for hiding/showing, similar to [this](https://play.google.com/store/apps/details?id=com.tapadoo.alerter_demo)

Bonus: publish the sample to the play store so that we don't need to clone/build the project :)

**Comment by aritraroy** [comment]
The idea of a sample project is to demonstrate the usage of the library and its various APIs. The current sample project clearly does that well. 

Publishing a sample app in Play Store seems like an overkill currently, IMHO.
