### ISSUE TITLE
Cannot immediately dismiss Flashbar instance

### ISSUE THREAD

**Issue by wrbl606** [aritraroy/Flashbar#22]
Consider this code: 
```kotlin
class MainActivity : AppCompatActivity() {

    var flashbar : Flashbar? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        setupFlashbar()
    }

    override fun onStart() {
        super.onStart()

        flashbar?.show()
        flashbar?.dismiss()
    }

    fun setupFlashbar() {
        flashbar = Flashbar.Builder(this)
                .message("Test")
                .gravity(Flashbar.Gravity.BOTTOM)
                .build()
    }
}
```

If you run it, you'll see that flashbar is still shown, regardless of `flashbar?.dismiss()` being called. 
I'm not sure if this is a bug, since method `isShowing()` is provided so case like that was considered. If so, please add something like `onFlashbarShown` interface so it's possible to make sure that flashbar is dismissed.

Thanks for reading this. The library is great ♥

**Comment by sondangpangaribuan** [comment]
any solution for this ?????

**Comment by wrbl606** [comment]
@sondangpangaribuan Yes, but it is only a dirty quick fix:
Using [debouncer library](https://github.com/wrbl606/android-debouncer) you can delay your `.dismiss()` call to make sure that flashbar is fully shown. Show/hide animation continues for 300 ms. 
This is a code example:
```java
if (loadingFlashbar.isShowing()) {
     Debouncer.debounce("hide-loading-snackbar", new Runnable() {
        @Override
        public void run() {
            loadingFlashbar.dismiss();
        }
    }, 300);
} else {
    loadingFlashbar.dismiss();
}
```

**Comment by sondangpangaribuan** [comment]
thank you

**Comment by AlaaElrifaie** [comment]
> @sondangpangaribuan Yes, but it is only a dirty quick fix:
> Using [debouncer library](https://github.com/wrbl606/android-debouncer) you can delay your `.dismiss()` call to make sure that flashbar is fully shown. Show/hide animation continues for 300 ms.
> This is a code example:
> 
> ```java
> if (loadingFlashbar.isShowing()) {
>      Debouncer.debounce("hide-loading-snackbar", new Runnable() {
>         @Override
>         public void run() {
>             loadingFlashbar.dismiss();
>         }
>     }, 300);
> } else {
>     loadingFlashbar.dismiss();
> }
> ```

The bad thing is that we cannot use this if we migrate to the AndroidX libraries. Gonna have to find another work around to this.

**Comment by wrbl606** [comment]
> > @sondangpangaribuan Yes, but it is only a dirty quick fix:
> > Using [debouncer library](https://github.com/wrbl606/android-debouncer) you can delay your `.dismiss()` call to make sure that flashbar is fully shown. Show/hide animation continues for 300 ms.
> > This is a code example:
> > ```java
> > if (loadingFlashbar.isShowing()) {
> >      Debouncer.debounce("hide-loading-snackbar", new Runnable() {
> >         @Override
> >         public void run() {
> >             loadingFlashbar.dismiss();
> >         }
> >     }, 300);
> > } else {
> >     loadingFlashbar.dismiss();
> > }
> > ```
> 
> The bad thing is that we cannot use this if we migrate to the AndroidX libraries.
> Gonna have to find another work around to this.

I don't think that this debouncer will introduce any issues while migrating to AndroidX - it does have [no dependencies](https://github.com/wrbl606/android-debouncer/blob/master/debouncer/build.gradle). In fact, it's just one `.java` [file](https://github.com/wrbl606/android-debouncer/blob/master/debouncer/src/main/java/com/github/xolan/android/debouncer/Debouncer.java) wrapped with module and deployed to bintray.

Still, Flashbar library fix would be nice.
