### ISSUE TITLE
Bug in sample: can create 2, and then unable to dismiss one

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [aritraroy/Flashbar#6]
See attached video:

[device-2018-05-06-215703.zip](https://github.com/aritraroy/Flashbar/files/1977925/device-2018-05-06-215703.zip)

**Comment by aritraroy** [comment]
This is not how it is supposed to be used. Every time you click "Show" a new instance of flashbar is created and shown. Now when you dismiss, you are only dismissing the last flashbar (assuming that you are keeping a reference to that only).

As you do not have any reference to the other flashbars, you are not able to dismiss them. If you maintain a list of all the flashbar references, you can dismiss all of them.

This is not a bug, but this is how it should function. We have plans to bring FlashbarManager to handle all these references and dismiss all at once automatically for you.

**Comment by AndroidDeveloperLB** [comment]
So it's a bug in the sample, but why close it then?
I've noticed another issue: it doesn't get re-shown after the activity is recreated upon orientation change.

**Comment by aritraroy** [comment]
Not an issue with the library, that's why. The sample is just for demonstrating the API usage.

This library is not meant to be lifecycle aware. You should handle its visibility on activity configuration changes yourself.
